# Generated by Django 5.2 on 2025-04-11 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='project_id',
            field=models.IntegerField(default=1, verbose_name='プロジェクトID'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='開始日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
