# Generated by Django 5.1.8 on 2025-04-11 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_end_date_schedule_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='開始日'),
        ),
    ]
