# Generated by Django 5.2 on 2025-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_schedule_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='内容'),
        ),
    ]
