# Generated by Django 5.2 on 2025-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_schedule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(verbose_name='タイトル'),
        ),
    ]
