# Generated by Django 5.1.8 on 2025-04-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_schedule_description_alter_schedule_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reminder_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タスクID'),
        ),
    ]
